### ISSUE TITLE
Resolver URL returns 404

### ISSUE THREAD

**Issue by imsj2016** [ihji/sbt-antlr4#12]
README.md specifies
resolvers += "simplytyped" at "http://simplytyped.github.io/repo/releases"
however, this returns a 404

**Comment by ihji** [comment]
README.md updated. Now we use bintray instead of github pages. Thanks for your report.

**Comment by amanjpro** [comment]
The version in bintray cannot resolve ANTLR 4.5!

My configuration is: Scala v 2.11.8 and SBT 0.13.8.

It used to work in the older repository.

**Comment by ihji** [comment]
@amanjpro I published all 0.7.x versions to bintray now. You can use 0.7.4 version with bintray repo.

**Comment by amanjpro** [comment]
@ihji thank you, it fixed the problem
