### ISSUE TITLE
Invalid instructions

### ISSUE THREAD

**Issue by Khalian** [ihji/sbt-antlr4#27]
I set up your plugin, But I got

```
/Users/arunavs/Modulo12/build.sbt:15: error: type mismatch;
 found   : sbt.internal.DslEntry
 required: sbt.Def.SettingsDefinition
    enablePlugins(Antlr4Plugin),
```

Please provide proper instructions for setting up and preferably a sample project actually setting this up.

**Comment by ihji** [comment]
What sbt version did you use?

**Comment by Khalian** [comment]
oh yea good point. i switched to 1.47. seems to pass correctly.
