### ISSUE TITLE
bintray is deprecated, plugin is not (always) downloadable

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [ihji/sbt-antlr4#31]
First, thanks for useful plugin!

It's not downloadable from bintray right now (Apr 12).

See
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

> April 12th, 26th, 2021 - We will have some short service brown-outs to remind users about the services that are going away on May 1st. (Specific hours will be advertised in the Bintray status page.)

This is an error I am getting:

download error: Caught java.io.IOException: Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml (Server returned HTTP response code: 502 for URL: https://dl.bintray.com/sbt/sbt-plugin-releases/com.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml) while downloading https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.simplytyped/sbt-antlr4/scala_2.12/sbt_1.0/0.8.3/ivys/ivy.xml

**Comment by ihji** [comment]
thanks for the ping. will work on publishing to maven central instead of bintray.

**Comment by ihji** [comment]
Migrated to sonatype / maven central. Thanks!
